# Generated by Django 4.1.1 on 2022-10-20 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_items_musics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Musics',
            new_name='Music',
        ),
    ]
